fix(dannysexpansion): fix klifour spawn
`Failed to save chunk -152,0
 java.lang.RuntimeException: StructurePiece "bottomtextdanny.dannys_expansion.content.structures.anglerstreasure.AnglersTreasurePiece": "null" missing ID Mapping, Modder see MapGenStructureIO`